spring:
  application:
    name: shop-dev-java
  datasource:
    url: jdbc:mysql://localhost:33336/shopdevjava
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true